import {
  InventoryAlert,
  InventoryItem,
  InventoryTransaction,
  InventoryTrendPoint,
  StockCategorySummary,
} from "@/types/inventory";

export const WAREHOUSES = [
  "Main Warehouse",
  "Raw Material Warehouse",
  "Packaging Warehouse",
];

export const RAW_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: "item_flour",
    itemCode: "RM-FLOUR",
    itemName: "Wheat Flour",
    category: "Raw Materials",
    warehouse: "Raw Material Warehouse",
    warehouseId: "wh_raw",
    unit: "kg",
    quantityOnHand: 28500,
    reservedQuantity: 3200,
    reorderLevel: 8000,
    normalStockLevel: 12000,
    unitCost: 0.85,
    locationBin: "Silo-A1 / Bay-01",
    minOrderQuantity: 10000,
    leadTimeDays: 5,
    createdAt: "2026-01-10T08:00:00.000Z",
    updatedAt: "2026-10-01T08:30:00.000Z",
  },
  {
    id: "item_sugar",
    itemCode: "RM-SUGAR",
    itemName: "Sugar",
    category: "Raw Materials",
    warehouse: "Raw Material Warehouse",
    warehouseId: "wh_raw",
    unit: "kg",
    quantityOnHand: 9200,
    reservedQuantity: 1100,
    reorderLevel: 4000,
    normalStockLevel: 8000,
    unitCost: 1.20,
    locationBin: "Rack-B03",
    minOrderQuantity: 3000,
    leadTimeDays: 3,
    createdAt: "2026-01-10T08:00:00.000Z",
    updatedAt: "2026-10-01T09:15:00.000Z",
  },
  {
    id: "item_cocoa",
    itemCode: "RM-COCOA",
    itemName: "Cocoa Powder",
    category: "Raw Materials",
    warehouse: "Raw Material Warehouse",
    warehouseId: "wh_raw",
    unit: "kg",
    quantityOnHand: 1420,
    reservedQuantity: 320,
    reorderLevel: 1500,
    normalStockLevel: 3000,
    unitCost: 4.60,
    locationBin: "Rack-B07 (Climate Controlled)",
    minOrderQuantity: 1000,
    leadTimeDays: 7,
    createdAt: "2026-01-12T09:00:00.000Z",
    updatedAt: "2026-10-01T10:00:00.000Z",
  },
  {
    id: "item_palmoil",
    itemCode: "RM-PALMOIL",
    itemName: "Vegetable Shortening",
    category: "Raw Materials",
    warehouse: "Raw Material Warehouse",
    warehouseId: "wh_raw",
    unit: "kg",
    quantityOnHand: 5800,
    reservedQuantity: 900,
    reorderLevel: 3000,
    normalStockLevel: 6000,
    unitCost: 1.75,
    locationBin: "Tank-C02",
    minOrderQuantity: 2500,
    leadTimeDays: 4,
    createdAt: "2026-01-15T11:00:00.000Z",
    updatedAt: "2026-10-01T07:45:00.000Z",
  },
  {
    id: "item_salt",
    itemCode: "RM-SALT",
    itemName: "Refined Salt",
    category: "Raw Materials",
    warehouse: "Main Warehouse",
    warehouseId: "wh_main",
    unit: "kg",
    quantityOnHand: 2400,
    reservedQuantity: 250,
    reorderLevel: 800,
    normalStockLevel: 2000,
    unitCost: 0.40,
    locationBin: "Bin-A04",
    minOrderQuantity: 1000,
    leadTimeDays: 2,
    createdAt: "2026-01-20T10:00:00.000Z",
    updatedAt: "2026-09-30T14:00:00.000Z",
  },
  {
    id: "item_wrapper",
    itemCode: "PKG-WRAP",
    itemName: "Biscuit Wrapper",
    category: "Packaging Materials",
    warehouse: "Packaging Warehouse",
    warehouseId: "wh_pkg",
    unit: "meters",
    quantityOnHand: 15400,
    reservedQuantity: 2400,
    reorderLevel: 18000,
    normalStockLevel: 35000,
    unitCost: 0.15,
    locationBin: "Aisle-P1 / Bay-03",
    minOrderQuantity: 20000,
    leadTimeDays: 6,
    createdAt: "2026-01-10T08:00:00.000Z",
    updatedAt: "2026-10-01T06:30:00.000Z",
  },
  {
    id: "item_box",
    itemCode: "PKG-BOX",
    itemName: "Biscuit Box",
    category: "Packaging Materials",
    warehouse: "Packaging Warehouse",
    warehouseId: "wh_pkg",
    unit: "pieces",
    quantityOnHand: 920,
    reservedQuantity: 150,
    reorderLevel: 2500,
    normalStockLevel: 6000,
    unitCost: 0.65,
    locationBin: "Aisle-P2 / Pallet-08",
    minOrderQuantity: 5000,
    leadTimeDays: 5,
    createdAt: "2026-01-10T08:00:00.000Z",
    updatedAt: "2026-10-01T09:00:00.000Z",
  },
  {
    id: "item_carton",
    itemCode: "PKG-CARTON",
    itemName: "Corrugated Shipper Carton",
    category: "Packaging Materials",
    warehouse: "Main Warehouse",
    warehouseId: "wh_main",
    unit: "pieces",
    quantityOnHand: 3400,
    reservedQuantity: 400,
    reorderLevel: 1200,
    normalStockLevel: 3000,
    unitCost: 1.45,
    locationBin: "Aisle-M4 / Bay-12",
    minOrderQuantity: 2000,
    leadTimeDays: 4,
    createdAt: "2026-01-14T09:30:00.000Z",
    updatedAt: "2026-09-30T17:00:00.000Z",
  },
];

export const INVENTORY_STOCK_TREND_DATA: InventoryTrendPoint[] = [
  { date: "2026-09-25", dayLabel: "Fri (Sep 25)", stockReceived: 10000, productionConsumption: 6200, currentStock: 63800 },
  { date: "2026-09-26", dayLabel: "Sat (Sep 26)", stockReceived: 0, productionConsumption: 7100, currentStock: 56700 },
  { date: "2026-09-27", dayLabel: "Sun (Sep 27)", stockReceived: 0, productionConsumption: 4800, currentStock: 51900 },
  { date: "2026-09-28", dayLabel: "Mon (Sep 28)", stockReceived: 15000, productionConsumption: 8200, currentStock: 58700 },
  { date: "2026-09-29", dayLabel: "Tue (Sep 29)", stockReceived: 5000, productionConsumption: 7900, currentStock: 55800 },
  { date: "2026-09-30", dayLabel: "Wed (Sep 30)", stockReceived: 12000, productionConsumption: 6900, currentStock: 60900 },
  { date: "2026-10-01", dayLabel: "Today (Thu)", stockReceived: 8000, productionConsumption: 6500, currentStock: 62400 },
];

export const STOCK_CATEGORY_DATA: StockCategorySummary[] = [
  {
    category: "Raw Materials",
    itemCount: 5,
    totalQuantity: 47320,
    totalValue: 52140.0,
    color: "#06b6d4", // cyan
  },
  {
    category: "Packaging Materials",
    itemCount: 3,
    totalQuantity: 19720,
    totalValue: 7838.0,
    color: "#a855f7", // purple
  },
];

export const INITIAL_INVENTORY_ALERTS: InventoryAlert[] = [
  {
    id: "alt_box",
    itemId: "item_box",
    itemCode: "PKG-BOX",
    itemName: "Biscuit Box",
    category: "Packaging Materials",
    availableQuantity: 770,
    reorderLevel: 2500,
    unit: "pieces",
    severity: "Critical",
    status: "Critical",
    message: "PKG-BOX is in critical stock state (available stock is 770 pcs, below 50% of 2,500 reorder point).",
    recommendedAction: "Create Purchase Request",
  },
  {
    id: "alt_cocoa",
    itemId: "item_cocoa",
    itemCode: "RM-COCOA",
    itemName: "Cocoa Powder",
    category: "Raw Materials",
    availableQuantity: 1100,
    reorderLevel: 1500,
    unit: "kg",
    severity: "Warning",
    status: "Low Stock",
    message: "RM-COCOA is approaching reorder level (1,100 kg available vs 1,500 kg reorder trigger).",
    recommendedAction: "Create Purchase Request",
  },
  {
    id: "alt_wrapper",
    itemId: "item_wrapper",
    itemCode: "PKG-WRAP",
    itemName: "Biscuit Wrapper",
    category: "Packaging Materials",
    availableQuantity: 13000,
    reorderLevel: 18000,
    unit: "meters",
    severity: "Warning",
    status: "Low Stock",
    message: "PKG-WRAP stock is below the recommended level for upcoming Line 1 & Line 2 runs.",
    recommendedAction: "Review Consumption",
  },
  {
    id: "alt_flour",
    itemId: "item_flour",
    itemCode: "RM-FLOUR",
    itemName: "Wheat Flour",
    category: "Raw Materials",
    availableQuantity: 25300,
    reorderLevel: 8000,
    unit: "kg",
    severity: "Info",
    status: "Overstock",
    message: "RM-FLOUR inventory is significantly above the normal stock level (25.3T on hand).",
    recommendedAction: "Check Upcoming Production",
  },
];

export const INITIAL_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: "trx_001",
    transactionId: "TRX-2026-0891",
    date: "2026-10-01T09:45:00.000Z",
    itemId: "item_flour",
    itemCode: "RM-FLOUR",
    itemName: "Wheat Flour",
    warehouse: "Raw Material Warehouse",
    transactionType: "Receipt",
    quantity: 10000,
    unit: "kg",
    reference: "PO-0041 (GRN-882)",
    notes: "Supplier intake verified with Certificate of Analysis (CoA).",
    performedBy: "Marcus Chen (Inventory Head)",
  },
  {
    id: "trx_002",
    transactionId: "TRX-2026-0892",
    date: "2026-10-01T08:15:00.000Z",
    itemId: "item_sugar",
    itemCode: "RM-SUGAR",
    itemName: "Sugar",
    warehouse: "Raw Material Warehouse",
    transactionType: "Production Consumption",
    quantity: -1200,
    unit: "kg",
    reference: "PROD-00001 (Classic Butter)",
    notes: "Issued to Mixer 1 for morning shift batch execution.",
    performedBy: "Sarah Jenkins (Production Lead)",
  },
  {
    id: "trx_003",
    transactionId: "TRX-2026-0893",
    date: "2026-10-01T07:30:00.000Z",
    itemId: "item_cocoa",
    itemCode: "RM-COCOA",
    itemName: "Cocoa Powder",
    warehouse: "Raw Material Warehouse",
    transactionType: "Production Consumption",
    quantity: -350,
    unit: "kg",
    reference: "PROD-00002 (Chocolate)",
    notes: "Batch recipe dosing automated dispension.",
    performedBy: "Sarah Jenkins (Production Lead)",
  },
  {
    id: "trx_004",
    transactionId: "TRX-2026-0894",
    date: "2026-09-30T16:20:00.000Z",
    itemId: "item_wrapper",
    itemCode: "PKG-WRAP",
    itemName: "Biscuit Wrapper",
    warehouse: "Packaging Warehouse",
    transactionType: "Transfer",
    quantity: -2500,
    unit: "meters",
    reference: "TRF-088 (Line 1 Buffer)",
    notes: "Staged at Packaging Machine 1 active reel spindle.",
    performedBy: "Dave Miller (Warehouse Tech)",
  },
  {
    id: "trx_005",
    transactionId: "TRX-2026-0895",
    date: "2026-09-30T14:10:00.000Z",
    itemId: "item_box",
    itemCode: "PKG-BOX",
    itemName: "Biscuit Box",
    warehouse: "Packaging Warehouse",
    transactionType: "Adjustment",
    quantity: -80,
    unit: "pieces",
    reference: "ADJ-102 (Cycle Count)",
    notes: "Damaged packaging cartons discarded following water leak inspection.",
    performedBy: "Marcus Chen (Inventory Head)",
  },
  {
    id: "trx_006",
    transactionId: "TRX-2026-0896",
    date: "2026-09-30T11:00:00.000Z",
    itemId: "item_carton",
    itemCode: "PKG-CARTON",
    itemName: "Corrugated Shipper Carton",
    warehouse: "Main Warehouse",
    transactionType: "Receipt",
    quantity: 1500,
    unit: "pieces",
    reference: "PO-0039 (GRN-874)",
    notes: "Delivered on 3 master wooden pallets.",
    performedBy: "Dave Miller (Warehouse Tech)",
  },
  {
    id: "trx_007",
    transactionId: "TRX-2026-0897",
    date: "2026-09-29T15:45:00.000Z",
    itemId: "item_sugar",
    itemCode: "RM-SUGAR",
    itemName: "Sugar",
    warehouse: "Raw Material Warehouse",
    transactionType: "Return",
    quantity: 150,
    unit: "kg",
    reference: "RET-024 (Excess Scrap Reversal)",
    notes: "Unused sealed bags returned from Line 3 staging area.",
    performedBy: "Sarah Jenkins (Production Lead)",
  },
];
