import {
  MachineItem,
  MaintenanceAlert,
  MaintenanceRecord,
  SensorReadingPoint,
} from "@/types/machines";

// Helper to generate 24-hour realistic sensor history points
function generateSensorHistory(
  baseTemp: number,
  tempFluctuation: number,
  tempLimit: number,
  baseVib: number,
  vibFluctuation: number,
  vibLimit: number,
  baseLoad: number,
  basePower: number
): SensorReadingPoint[] {
  const hours = [
    "00:00", "02:00", "04:00", "06:00", "08:00", "10:00",
    "12:00", "14:00", "16:00", "18:00", "20:00", "22:00", "Now"
  ];

  return hours.map((hour, idx) => {
    // Add realistic deterministic variations
    const varianceFactor = Math.sin(idx * 0.8) * 0.7 + (idx > 8 ? 0.6 : 0.0);
    const temp = Number((baseTemp + varianceFactor * tempFluctuation).toFixed(1));
    const vib = Number((baseVib + varianceFactor * vibFluctuation).toFixed(2));
    const load = Math.min(100, Math.max(0, Math.round(baseLoad + varianceFactor * 6)));
    const power = Number((basePower + varianceFactor * 2.5).toFixed(1));

    return {
      timestamp: hour,
      hourLabel: hour,
      temperature: temp,
      temperatureThreshold: tempLimit,
      vibration: vib,
      vibrationThreshold: vibLimit,
      motorLoad: load,
      powerConsumption: power,
    };
  });
}

export const INITIAL_MACHINES: MachineItem[] = [
  {
    id: "mch_001",
    machineCode: "MCH-001",
    machineName: "Baking Oven 1",
    machineType: "Continuous Tunnel Oven",
    status: "Running",
    location: "Line 1 — Thermal Bay A",
    installationDate: "2023-03-15",
    operatingHours: 5420,
    downtimeMinutes: 0,
    utilization: 96.4,
    lastMaintenanceDate: "2026-09-15",
    nextMaintenanceDate: "2026-10-15",
    currentTemperature: 192.5,
    currentVibration: 1.25,
    currentMotorLoad: 88,
    currentPower: 45.2,
    riskLevel: "Low",
    riskScore: 14,
    sensorHistory: generateSensorHistory(190, 3.5, 210, 1.1, 0.25, 3.0, 86, 44),
    maintenanceHistory: [
      {
        id: "mnt_001",
        maintenanceId: "MNT-2026-0038",
        machineId: "mch_001",
        date: "2026-09-15T08:00:00.000Z",
        type: "Preventive",
        description: "Burner nozzle cleaning, gas pressure calibration, and conveyor chain lubrication.",
        technician: "Viktor Vance (Chief Mech Tech)",
        downtimeHours: 2.5,
        cost: 320,
        status: "Completed",
      },
      {
        id: "mnt_002",
        maintenanceId: "MNT-2026-0021",
        machineId: "mch_001",
        date: "2026-08-10T09:00:00.000Z",
        type: "Inspection",
        description: "Thermocouple calibration check and heat insulation thermography audit.",
        technician: "Elena Rostova (QA/Reliability)",
        downtimeHours: 1.0,
        cost: 150,
        status: "Completed",
      },
    ],
    prediction: {
      id: "pred_001",
      machineId: "mch_001",
      machineCode: "MCH-001",
      machineName: "Baking Oven 1",
      riskScore: 14,
      riskLevel: "Low",
      mainRiskFactor: "Normal thermal stability",
      prediction: "Optimal equipment health with minimal vibration and steady thermal gradient.",
      recommendedAction: "Continue standard operating cycle. Next scheduled PM in 14 days.",
      confidenceScore: 94.2,
      predictedFailureWindow: "> 30 days",
      predictionDate: "2026-10-01",
    },
  },
  {
    id: "mch_002",
    machineCode: "MCH-002",
    machineName: "Packaging Machine 1",
    machineType: "Flow Wrap Packager",
    status: "Running",
    location: "Line 1 — End of Line Packaging",
    installationDate: "2023-08-20",
    operatingHours: 4180,
    downtimeMinutes: 10,
    utilization: 88.5,
    lastMaintenanceDate: "2026-09-10",
    nextMaintenanceDate: "2026-10-08",
    currentTemperature: 42.0,
    currentVibration: 3.42,
    currentMotorLoad: 74,
    currentPower: 18.4,
    riskLevel: "Medium",
    riskScore: 57,
    sensorHistory: generateSensorHistory(40, 4.0, 55, 2.8, 0.8, 3.5, 72, 17.5),
    maintenanceHistory: [
      {
        id: "mnt_003",
        maintenanceId: "MNT-2026-0035",
        machineId: "mch_002",
        date: "2026-09-10T14:00:00.000Z",
        type: "Preventive",
        description: "Cutter blade sharpening, heating jaw Teflon tape replacement, and optical eye calibration.",
        technician: "Dave Miller (Automation Specialist)",
        downtimeHours: 1.5,
        cost: 210,
        status: "Completed",
      },
    ],
    prediction: {
      id: "pred_002",
      machineId: "mch_002",
      machineCode: "MCH-002",
      machineName: "Packaging Machine 1",
      riskScore: 57,
      riskLevel: "Medium",
      mainRiskFactor: "Increasing vibration",
      prediction: "Drive roller spindle vibration has drifted +18% above 30-day baseline.",
      recommendedAction: "Inspect bearings and drive components during the next planned sanitation changeover.",
      confidenceScore: 88.6,
      predictedFailureWindow: "7-10 days",
      predictionDate: "2026-10-01",
    },
  },
  {
    id: "mch_003",
    machineCode: "MCH-003",
    machineName: "Mixer 1",
    machineType: "High-Shear Batch Mixer",
    status: "Running",
    location: "Batch Mixing Zone — Station 1",
    installationDate: "2022-11-05",
    operatingHours: 6840,
    downtimeMinutes: 15,
    utilization: 91.2,
    lastMaintenanceDate: "2026-09-02",
    nextMaintenanceDate: "2026-10-04",
    currentTemperature: 28.0,
    currentVibration: 1.62,
    currentMotorLoad: 92,
    currentPower: 32.8,
    riskLevel: "Low",
    riskScore: 22,
    sensorHistory: generateSensorHistory(26, 3.0, 45, 1.4, 0.35, 3.0, 90, 31),
    maintenanceHistory: [
      {
        id: "mnt_004",
        maintenanceId: "MNT-2026-0031",
        machineId: "mch_003",
        date: "2026-09-02T07:30:00.000Z",
        type: "Preventive",
        description: "Main gearbox oil replacement, paddle clearance inspection, and seal grease refill.",
        technician: "Viktor Vance (Chief Mech Tech)",
        downtimeHours: 3.0,
        cost: 480,
        status: "Completed",
      },
    ],
    prediction: {
      id: "pred_003",
      machineId: "mch_003",
      machineCode: "MCH-003",
      machineName: "Mixer 1",
      riskScore: 22,
      riskLevel: "Low",
      mainRiskFactor: "Routine maintenance cycle approaching",
      prediction: "Motor torque and gearbox telemetry are within nominal limits.",
      recommendedAction: "Maintenance due in 3 days. Prepare synthetic food-grade gearbox lubricant.",
      confidenceScore: 92.0,
      predictedFailureWindow: "> 21 days",
      predictionDate: "2026-10-01",
    },
  },
  {
    id: "mch_004",
    machineCode: "MCH-004",
    machineName: "Baking Oven 2",
    machineType: "Rotary Deck Oven",
    status: "Warning",
    location: "Line 2 — Specialty Baking Bay",
    installationDate: "2023-01-18",
    operatingHours: 4950,
    downtimeMinutes: 48,
    utilization: 74.2,
    lastMaintenanceDate: "2026-08-25",
    nextMaintenanceDate: "2026-10-02",
    currentTemperature: 86.4,
    currentVibration: 4.82,
    currentMotorLoad: 68,
    currentPower: 38.6,
    riskLevel: "High",
    riskScore: 82,
    sensorHistory: generateSensorHistory(80, 8.5, 95, 3.8, 1.4, 4.0, 65, 36),
    maintenanceHistory: [
      {
        id: "mnt_005",
        maintenanceId: "MNT-2026-0028",
        machineId: "mch_004",
        date: "2026-08-25T11:00:00.000Z",
        type: "Corrective",
        description: "Replaced zone 2 faulty temperature thermocouple sensor probe.",
        technician: "Dave Miller (Automation Specialist)",
        downtimeHours: 4.0,
        cost: 590,
        status: "Completed",
      },
      {
        id: "mnt_006",
        maintenanceId: "MNT-2026-0012",
        machineId: "mch_004",
        date: "2026-07-14T09:00:00.000Z",
        type: "Inspection",
        description: "Thermal exhaust blower vibration analysis and fan dynamic balancing.",
        technician: "Viktor Vance (Chief Mech Tech)",
        downtimeHours: 2.0,
        cost: 250,
        status: "Completed",
      },
    ],
    prediction: {
      id: "pred_004",
      machineId: "mch_004",
      machineCode: "MCH-004",
      machineName: "Baking Oven 2",
      riskScore: 82,
      riskLevel: "High",
      mainRiskFactor: "Increasing temperature trend & blower vibration",
      prediction: "Machine health is deteriorating compared with its recent operating pattern.",
      recommendedAction: "Review Oven-02 operating conditions and schedule inspection during next planned downtime.",
      confidenceScore: 91.5,
      predictedFailureWindow: "24-48 hours",
      predictionDate: "2026-10-01",
    },
  },
  {
    id: "mch_005",
    machineCode: "MCH-005",
    machineName: "Packaging Machine 2",
    machineType: "Secondary Box Cartoner",
    status: "Maintenance",
    location: "Line 2 — Secondary Boxing Bay",
    installationDate: "2022-09-10",
    operatingHours: 7210,
    downtimeMinutes: 120,
    utilization: 0.0,
    lastMaintenanceDate: "2026-10-01",
    nextMaintenanceDate: "2026-10-01",
    currentTemperature: 22.0,
    currentVibration: 0.0,
    currentMotorLoad: 0,
    currentPower: 0.0,
    riskLevel: "Critical",
    riskScore: 94,
    sensorHistory: generateSensorHistory(22, 1.0, 50, 0.0, 0.0, 3.5, 0, 0),
    maintenanceHistory: [
      {
        id: "mnt_007",
        maintenanceId: "MNT-2026-0042",
        machineId: "mch_005",
        date: "2026-10-01T06:00:00.000Z",
        type: "Corrective",
        description: "Emergency conveyor timing belt replacement and pneumatic carton suction cup overhaul.",
        technician: "Viktor Vance (Chief Mech Tech)",
        downtimeHours: 2.0,
        cost: 650,
        status: "In Progress",
      },
    ],
    prediction: {
      id: "pred_005",
      machineId: "mch_005",
      machineCode: "MCH-005",
      machineName: "Packaging Machine 2",
      riskScore: 94,
      riskLevel: "Critical",
      mainRiskFactor: "Conveyor timing belt mechanical failure",
      prediction: "Offline under emergency repair. Drive motor re-alignment required after belt installation.",
      recommendedAction: "Complete mechanical overhaul, verify belt tensioning, and run 15-min dry cycle test before resuming Line 2.",
      confidenceScore: 98.2,
      predictedFailureWindow: "Active Stoppage",
      predictionDate: "2026-10-01",
    },
  },
];

export const INITIAL_MAINTENANCE_ALERTS: MaintenanceAlert[] = [
  {
    id: "alt_mch_004",
    machineId: "mch_004",
    machineCode: "MCH-004",
    machineName: "Baking Oven 2",
    severity: "High",
    reason: "⚠ Baking Oven 2 has increasing temperature readings and elevated blower vibration (4.82 mm/s vs 4.0 limit).",
    recommendedAction: "Schedule thermal inspection & blower bearing check during the next shift changeover.",
    timestamp: "18 mins ago",
  },
  {
    id: "alt_mch_002",
    machineId: "mch_002",
    machineCode: "MCH-002",
    machineName: "Packaging Machine 1",
    severity: "Medium",
    reason: "⚠ Packaging Machine 1 vibration is above its recent baseline (+18% drift on flow wrap drive spindle).",
    recommendedAction: "Inspect bearings and drive components during scheduled sanitation stop.",
    timestamp: "45 mins ago",
  },
  {
    id: "alt_mch_003",
    machineId: "mch_003",
    machineCode: "MCH-003",
    machineName: "Mixer 1",
    severity: "Low",
    reason: "Maintenance due for Mixer 1: 500-hour preventive lubrication cycle in 3 days.",
    recommendedAction: "Assign technician to execute synthetic gearbox lubricant replenishment.",
    timestamp: "2 hours ago",
  },
];
