import {
  SupplierItem,
  PurchaseRequest,
  PurchaseOrderItem,
  MaterialProcurementRow,
  ProcurementAlert,
  ProcurementSpendTrendPoint,
  CategorySpendPoint,
  MaterialCategory,
} from "@/types/procurement";

export const INITIAL_SUPPLIERS: SupplierItem[] = [
  {
    id: "sup_001",
    supplierCode: "SUP-001",
    supplierName: "Odisha Agro Foods Pvt Ltd",
    category: "Raw Materials",
    contactPerson: "Alok Patnaik",
    phone: "+91 98610 24810",
    email: "sales@odishaagrofoods.in",
    rating: 4.8,
    totalOrders: 42,
    onTimeDeliveryRate: 95.2,
    qualityScore: 98.0,
    averageLeadTimeDays: 4,
    totalSpend: 7850000,
    status: "Active",
    city: "Bhubaneswar, Odisha",
  },
  {
    id: "sup_002",
    supplierCode: "SUP-002",
    supplierName: "Eastern Packaging Solutions",
    category: "Packaging",
    contactPerson: "Debashis Mohanty",
    phone: "+91 94370 51920",
    email: "d.mohanty@easternpackaging.com",
    rating: 4.5,
    totalOrders: 36,
    onTimeDeliveryRate: 91.5,
    qualityScore: 94.8,
    averageLeadTimeDays: 6,
    totalSpend: 4250000,
    status: "Active",
    city: "Cuttack, Odisha",
  },
  {
    id: "sup_003",
    supplierCode: "SUP-003",
    supplierName: "Bharat Ingredients Supply",
    category: "Raw Materials",
    contactPerson: "Sunil Agarwal",
    phone: "+91 98200 67341",
    email: "orders@bharatingredients.co.in",
    rating: 4.7,
    totalOrders: 28,
    onTimeDeliveryRate: 96.0,
    qualityScore: 97.5,
    averageLeadTimeDays: 5,
    totalSpend: 3600000,
    status: "Active",
    city: "Kolkata, WB",
  },
  {
    id: "sup_004",
    supplierCode: "SUP-004",
    supplierName: "Sunrise Industrial Supplies",
    category: "Maintenance",
    contactPerson: "Ranjan Dash",
    phone: "+91 97760 11450",
    email: "contact@sunriseindustrial.org",
    rating: 4.2,
    totalOrders: 19,
    onTimeDeliveryRate: 88.0,
    qualityScore: 92.0,
    averageLeadTimeDays: 7,
    totalSpend: 1450000,
    status: "Active",
    city: "Rourkela, Odisha",
  },
  {
    id: "sup_005",
    supplierCode: "SUP-005",
    supplierName: "Prime Machinery Spares",
    category: "Spare Parts",
    contactPerson: "Kavita Rao",
    phone: "+91 99800 44321",
    email: "support@primemachinery.in",
    rating: 4.6,
    totalOrders: 15,
    onTimeDeliveryRate: 93.4,
    qualityScore: 96.2,
    averageLeadTimeDays: 8,
    totalSpend: 1850000,
    status: "Active",
    city: "Hyderabad, Telangana",
  },
];

export const INITIAL_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: "pr_001",
    requestId: "PR-2026-0041",
    requestedBy: "Tapan Nayak",
    department: "Production",
    material: "Wheat Flour (Refined)",
    category: "Raw Materials",
    quantity: 15000,
    unit: "kg",
    requiredDate: "2026-10-06",
    estimatedUnitCost: 32,
    estimatedTotalCost: 480000,
    priority: "Urgent",
    status: "Pending",
    supplierPreference: "Odisha Agro Foods Pvt Ltd",
    notes: "Main warehouse stock at critical reorder threshold (3.2 days buffer). Required for Line 1 batch runs.",
    createdAt: "2026-10-01T08:30:00.000Z",
  },
  {
    id: "pr_002",
    requestId: "PR-2026-0042",
    requestedBy: "Priya Sundaram",
    department: "Packaging",
    material: "Biscuit Wrapper Film (BOPP)",
    category: "Packaging",
    quantity: 8000,
    unit: "rolls",
    requiredDate: "2026-10-08",
    estimatedUnitCost: 45,
    estimatedTotalCost: 360000,
    priority: "High",
    status: "Pending",
    supplierPreference: "Eastern Packaging Solutions",
    notes: "Secondary wrapper stock low for Cream Biscuit packaging line. Scheduled shift changeover in 6 days.",
    createdAt: "2026-10-01T09:15:00.000Z",
  },
  {
    id: "pr_003",
    requestId: "PR-2026-0043",
    requestedBy: "Viktor Vance",
    department: "Maintenance",
    material: "Conveyor Timing Belt & Bearings",
    category: "Spare Parts",
    quantity: 6,
    unit: "units",
    requiredDate: "2026-10-05",
    estimatedUnitCost: 14500,
    estimatedTotalCost: 87000,
    priority: "High",
    status: "Approved",
    supplierPreference: "Prime Machinery Spares",
    notes: "Replacement set for Packaging Machine 2 emergency maintenance overhaul.",
    createdAt: "2026-09-30T14:00:00.000Z",
  },
  {
    id: "pr_004",
    requestId: "PR-2026-0044",
    requestedBy: "Marcus Brody",
    department: "QA/QC",
    material: "Food Grade Sanitizing Chemical",
    category: "Operations",
    quantity: 500,
    unit: "liters",
    requiredDate: "2026-10-12",
    estimatedUnitCost: 180,
    estimatedTotalCost: 90000,
    priority: "Normal",
    status: "Draft",
    supplierPreference: "Sunrise Industrial Supplies",
    notes: "Monthly sanitation chemical restocking for CIP system compliance.",
    createdAt: "2026-09-30T10:00:00.000Z",
  },
  {
    id: "pr_005",
    requestId: "PR-2026-0045",
    requestedBy: "Tapan Nayak",
    department: "Production",
    material: "Cocoa Powder (Pure Dark)",
    category: "Raw Materials",
    quantity: 3500,
    unit: "kg",
    requiredDate: "2026-10-10",
    estimatedUnitCost: 140,
    estimatedTotalCost: 490000,
    priority: "Normal",
    status: "Approved",
    supplierPreference: "Bharat Ingredients Supply",
    notes: "Allocated for Chocolate Biscuit planned production batch next week.",
    createdAt: "2026-09-29T16:45:00.000Z",
  },
  {
    id: "pr_006",
    requestId: "PR-2026-0046",
    requestedBy: "Priya Sundaram",
    department: "Packaging",
    material: "Corrugated Master Cartons",
    category: "Packaging",
    quantity: 12000,
    unit: "boxes",
    requiredDate: "2026-10-07",
    estimatedUnitCost: 18,
    estimatedTotalCost: 216000,
    priority: "Normal",
    status: "Converted to PO",
    supplierPreference: "Eastern Packaging Solutions",
    notes: "Converted to PO-2026-0082.",
    createdAt: "2026-09-28T11:20:00.000Z",
    convertedPoId: "PO-2026-0082",
  },
  {
    id: "pr_007",
    requestId: "PR-2026-0047",
    requestedBy: "Viktor Vance",
    department: "Maintenance",
    material: "Synthetic High-Temp Gear Lubricant",
    category: "Maintenance",
    quantity: 120,
    unit: "liters",
    requiredDate: "2026-10-15",
    estimatedUnitCost: 650,
    estimatedTotalCost: 78000,
    priority: "Low",
    status: "Approved",
    supplierPreference: "Sunrise Industrial Supplies",
    notes: "Baking oven drive gear replenishment scheduled for next PM cycle.",
    createdAt: "2026-09-28T09:00:00.000Z",
  },
  {
    id: "pr_008",
    requestId: "PR-2026-0048",
    requestedBy: "Ananya Mishra",
    department: "Inventory",
    material: "Pallet Stretch Wrap Film",
    category: "Packaging",
    quantity: 400,
    unit: "rolls",
    requiredDate: "2026-10-04",
    estimatedUnitCost: 280,
    estimatedTotalCost: 112000,
    priority: "High",
    status: "Rejected",
    supplierPreference: "Eastern Packaging Solutions",
    notes: "Excess stock already on floor; re-evaluate after end-of-month audit.",
    rejectionReason: "Sufficient buffer stock verified in Warehouse Bay 3.",
    createdAt: "2026-09-27T15:30:00.000Z",
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrderItem[] = [
  {
    id: "po_001",
    poNumber: "PO-2026-0081",
    supplierId: "sup_001",
    supplierName: "Odisha Agro Foods Pvt Ltd",
    orderDate: "2026-09-25",
    expectedDelivery: "2026-10-02",
    paymentTerms: "Net 30 Days",
    buyer: "Rajesh Sharma (Procurement Head)",
    items: [
      {
        id: "item_001",
        material: "Wheat Flour (Refined)",
        category: "Raw Materials",
        quantity: 20000,
        receivedQuantity: 12000,
        unit: "kg",
        unitPrice: 31.5,
        taxPercent: 5,
        totalPrice: 661500,
      },
    ],
    subtotal: 630000,
    taxAmount: 31500,
    totalAmount: 661500,
    paidAmount: 300000,
    paymentStatus: "Partially Paid",
    deliveryStatus: "In Transit",
    poStatus: "Partially Received",
    notes: "First shipment of 12,000 kg received on Sept 29. Balance 8,000 kg en route via dispatch challan OD-048.",
  },
  {
    id: "po_002",
    poNumber: "PO-2026-0082",
    supplierId: "sup_002",
    supplierName: "Eastern Packaging Solutions",
    orderDate: "2026-09-27",
    expectedDelivery: "2026-10-04",
    paymentTerms: "Advance 50%, Net 15",
    buyer: "Rajesh Sharma (Procurement Head)",
    items: [
      {
        id: "item_002",
        material: "Corrugated Master Cartons",
        category: "Packaging",
        quantity: 12000,
        receivedQuantity: 0,
        unit: "boxes",
        unitPrice: 17.5,
        taxPercent: 12,
        totalPrice: 235200,
      },
    ],
    subtotal: 210000,
    taxAmount: 25200,
    totalAmount: 235200,
    paidAmount: 117600,
    paymentStatus: "Partially Paid",
    deliveryStatus: "In Transit",
    poStatus: "Ordered",
    notes: "Shipment loaded from Cuttack plant. Expected dock arrival tomorrow morning.",
  },
  {
    id: "po_003",
    poNumber: "PO-2026-0083",
    supplierId: "sup_003",
    supplierName: "Bharat Ingredients Supply",
    orderDate: "2026-09-20",
    expectedDelivery: "2026-09-28",
    paymentTerms: "Net 30 Days",
    buyer: "Rajesh Sharma (Procurement Head)",
    items: [
      {
        id: "item_003",
        material: "Refined Cane Sugar (Grade S-30)",
        category: "Raw Materials",
        quantity: 10000,
        receivedQuantity: 0,
        unit: "kg",
        unitPrice: 42.0,
        taxPercent: 5,
        totalPrice: 441000,
      },
    ],
    subtotal: 420000,
    taxAmount: 21000,
    totalAmount: 441000,
    paidAmount: 0,
    paymentStatus: "Pending",
    deliveryStatus: "Delayed",
    poStatus: "Ordered",
    notes: "3 days past promised delivery schedule. Transporter truck breakdown reported near Kharagpur.",
  },
  {
    id: "po_004",
    poNumber: "PO-2026-0084",
    supplierId: "sup_005",
    supplierName: "Prime Machinery Spares",
    orderDate: "2026-09-18",
    expectedDelivery: "2026-09-26",
    paymentTerms: "Net 15 Days",
    buyer: "Viktor Vance (Chief Mech Tech)",
    items: [
      {
        id: "item_004",
        material: "Thermal Sensors & Thermocouples",
        category: "Spare Parts",
        quantity: 10,
        receivedQuantity: 10,
        unit: "units",
        unitPrice: 8500,
        taxPercent: 18,
        totalPrice: 100300,
      },
    ],
    subtotal: 85000,
    taxAmount: 15300,
    totalAmount: 100300,
    paidAmount: 100300,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
    poStatus: "Received",
    notes: "GRN-2026-0412 verified by QA electronics bench. Installed on Baking Oven 1.",
  },
  {
    id: "po_005",
    poNumber: "PO-2026-0085",
    supplierId: "sup_001",
    supplierName: "Odisha Agro Foods Pvt Ltd",
    orderDate: "2026-10-01",
    expectedDelivery: "2026-10-08",
    paymentTerms: "Net 30 Days",
    buyer: "Rajesh Sharma (Procurement Head)",
    items: [
      {
        id: "item_005",
        material: "Wheat Flour (Refined)",
        category: "Raw Materials",
        quantity: 15000,
        receivedQuantity: 0,
        unit: "kg",
        unitPrice: 32.0,
        taxPercent: 5,
        totalPrice: 504000,
      },
    ],
    subtotal: 480000,
    taxAmount: 24000,
    totalAmount: 504000,
    paidAmount: 0,
    paymentStatus: "Pending",
    deliveryStatus: "Not Shipped",
    poStatus: "Pending Approval",
    notes: "Awaiting Finance VP sign-off on PR-2026-0041 conversion.",
  },
  {
    id: "po_006",
    poNumber: "PO-2026-0086",
    supplierId: "sup_004",
    supplierName: "Sunrise Industrial Supplies",
    orderDate: "2026-09-24",
    expectedDelivery: "2026-10-03",
    paymentTerms: "Net 45 Days",
    buyer: "Viktor Vance (Chief Mech Tech)",
    items: [
      {
        id: "item_006",
        material: "Synthetic High-Temp Gear Lubricant",
        category: "Maintenance",
        quantity: 100,
        receivedQuantity: 100,
        unit: "liters",
        unitPrice: 620,
        taxPercent: 18,
        totalPrice: 73160,
      },
    ],
    subtotal: 62000,
    taxAmount: 11160,
    totalAmount: 73160,
    paidAmount: 0,
    paymentStatus: "Pending",
    deliveryStatus: "Delivered",
    poStatus: "Received",
    notes: "Received in good condition and transferred to Lubricant Storage Bay.",
  },
];

export const INITIAL_MATERIAL_STATUSES: MaterialProcurementRow[] = [
  {
    id: "mat_001",
    materialName: "Wheat Flour (Refined)",
    category: "Raw Materials",
    currentStock: 8200,
    requiredQuantity: 25000,
    onOrderQuantity: 20000,
    pendingQuantity: 8000,
    unit: "kg",
    expectedDelivery: "2026-10-02",
    status: "Reorder Required",
    primarySupplier: "Odisha Agro Foods Pvt Ltd",
  },
  {
    id: "mat_002",
    materialName: "Refined Cane Sugar",
    category: "Raw Materials",
    currentStock: 4100,
    requiredQuantity: 12000,
    onOrderQuantity: 10000,
    pendingQuantity: 10000,
    unit: "kg",
    expectedDelivery: "2026-09-28 (Overdue)",
    status: "Delayed",
    primarySupplier: "Bharat Ingredients Supply",
  },
  {
    id: "mat_003",
    materialName: "Pure Dark Cocoa Powder",
    category: "Raw Materials",
    currentStock: 2800,
    requiredQuantity: 4500,
    onOrderQuantity: 3500,
    pendingQuantity: 3500,
    unit: "kg",
    expectedDelivery: "2026-10-10",
    status: "On Order",
    primarySupplier: "Bharat Ingredients Supply",
  },
  {
    id: "mat_004",
    materialName: "Biscuit Wrapper Film (BOPP)",
    category: "Packaging",
    currentStock: 3400,
    requiredQuantity: 10000,
    onOrderQuantity: 8000,
    pendingQuantity: 8000,
    unit: "rolls",
    expectedDelivery: "2026-10-08",
    status: "Critical",
    primarySupplier: "Eastern Packaging Solutions",
  },
  {
    id: "mat_005",
    materialName: "Corrugated Master Cartons",
    category: "Packaging",
    currentStock: 14500,
    requiredQuantity: 15000,
    onOrderQuantity: 12000,
    pendingQuantity: 12000,
    unit: "boxes",
    expectedDelivery: "2026-10-04",
    status: "Sufficient",
    primarySupplier: "Eastern Packaging Solutions",
  },
];

export const INITIAL_PROCUREMENT_ALERTS: ProcurementAlert[] = [
  {
    id: "alt_001",
    severity: "High",
    relatedEntity: "PO-2026-0083",
    entityType: "PO",
    reason: "⚠ PO-2026-0083 is 3 days overdue (Refined Cane Sugar 10,000 kg). Transporter breakdown near Kharagpur.",
    recommendedAction: "Expedite alternate freight carrier or draw 2,000 kg emergency stock from safety reserve.",
    timestamp: "20 mins ago",
  },
  {
    id: "alt_002",
    severity: "High",
    relatedEntity: "Wheat Flour",
    entityType: "Material",
    reason: "⚠ Wheat Flour stock may require replenishment (Current: 8,200 kg vs 3-day minimum consumption 12,500 kg).",
    recommendedAction: "Approve pending PR-2026-0041 to release Purchase Order PO-2026-0085 immediately.",
    timestamp: "45 mins ago",
  },
  {
    id: "alt_003",
    severity: "Medium",
    relatedEntity: "PR-2026-0042",
    entityType: "PR",
    reason: "⚠ Purchase Request PR-2026-0042 (Biscuit Wrapper Film) is waiting for department head approval.",
    recommendedAction: "Review packaging order requirements and sign off to prevent packaging line stoppage next week.",
    timestamp: "2 hours ago",
  },
  {
    id: "alt_004",
    severity: "Medium",
    relatedEntity: "PO-2026-0081",
    entityType: "PO",
    reason: "⚠ Supplier delivery for PO-2026-0081 has balance 8,000 kg in transit. Dock clearance pending.",
    recommendedAction: "Pre-assign Quality inspector at Receiving Bay 2 for incoming AQL sampling.",
    timestamp: "4 hours ago",
  },
];

export const PROCUREMENT_SPEND_6_MONTHS: ProcurementSpendTrendPoint[] = [
  { period: "May 2026", purchaseSpend: 2450000, approvedSpend: 2320000, pendingSpend: 130000 },
  { period: "Jun 2026", purchaseSpend: 2890000, approvedSpend: 2710000, pendingSpend: 180000 },
  { period: "Jul 2026", purchaseSpend: 3150000, approvedSpend: 2980000, pendingSpend: 170000 },
  { period: "Aug 2026", purchaseSpend: 2950000, approvedSpend: 2800000, pendingSpend: 150000 },
  { period: "Sep 2026", purchaseSpend: 3420000, approvedSpend: 3120000, pendingSpend: 300000 },
  { period: "Oct 2026", purchaseSpend: 1860000, approvedSpend: 1580000, pendingSpend: 280000 },
];

export const CATEGORY_SPEND_DISTRIBUTION: CategorySpendPoint[] = [
  { category: "Raw Materials", spend: 11450000, orderCount: 70, color: "#10b981" },
  { category: "Packaging", spend: 4250000, orderCount: 36, color: "#06b6d4" },
  { category: "Spare Parts", spend: 1850000, orderCount: 15, color: "#f59e0b" },
  { category: "Maintenance", spend: 1450000, orderCount: 19, color: "#8b5cf6" },
  { category: "Operations", spend: 620000, orderCount: 8, color: "#ec4899" },
];
