import {
  EmployeeItem,
  AttendanceRecord,
  ShiftItem,
  WorkforceAllocationItem,
  ProductionLineWorkforce,
  OvertimeRecord,
  LeaveRequestRecord,
  WorkforceAlert,
  AttendanceTrendPoint,
  DepartmentProductivityItem,
} from "@/types/workforce";

export const INITIAL_EMPLOYEES: EmployeeItem[] = [
  {
    id: "emp_101",
    employeeId: "EMP-101",
    name: "Tapan Nayak",
    department: "Production",
    designation: "Production Supervisor",
    shift: "Morning Shift",
    phone: "+91 98610 33410",
    email: "tapan.nayak@factory.com",
    joiningDate: "2022-03-15",
    status: "Active",
    todayAttendance: "Present",
    checkInTime: "05:52 AM",
    productivityScore: 94.2,
    presentDaysCount: 22,
    absentDaysCount: 0,
    leaveDaysCount: 1,
    lateArrivalsCount: 0,
    attendanceRate: 98.5,
    unitsProducedToday: 18500,
    qualityPassRate: 98.2,
    overtimeHoursMonth: 14.5,
  },
  {
    id: "emp_102",
    employeeId: "EMP-102",
    name: "Viktor Vance",
    department: "Maintenance",
    designation: "Maintenance Manager",
    shift: "General Shift",
    phone: "+91 94370 88210",
    email: "viktor.vance@factory.com",
    joiningDate: "2021-08-01",
    status: "Active",
    todayAttendance: "Present",
    checkInTime: "08:45 AM",
    productivityScore: 96.0,
    presentDaysCount: 23,
    absentDaysCount: 0,
    leaveDaysCount: 0,
    lateArrivalsCount: 0,
    attendanceRate: 100.0,
    unitsProducedToday: 0,
    qualityPassRate: 99.1,
    overtimeHoursMonth: 18.0,
  },
  {
    id: "emp_103",
    employeeId: "EMP-103",
    name: "Elena Rostova",
    department: "Quality",
    designation: "Quality Supervisor",
    shift: "Morning Shift",
    phone: "+91 98200 44520",
    email: "elena.rostova@factory.com",
    joiningDate: "2023-01-10",
    status: "Active",
    todayAttendance: "Present",
    checkInTime: "05:58 AM",
    productivityScore: 95.8,
    presentDaysCount: 21,
    absentDaysCount: 1,
    leaveDaysCount: 1,
    lateArrivalsCount: 1,
    attendanceRate: 95.4,
    unitsProducedToday: 12400,
    qualityPassRate: 98.6,
    overtimeHoursMonth: 8.0,
  },
  {
    id: "emp_104",
    employeeId: "EMP-104",
    name: "Priya Sundaram",
    department: "Packaging",
    designation: "Machine Operator",
    shift: "Morning Shift",
    phone: "+91 97760 99310",
    email: "priya.sundaram@factory.com",
    joiningDate: "2023-05-20",
    status: "Active",
    todayAttendance: "Present",
    checkInTime: "06:05 AM",
    productivityScore: 89.5,
    presentDaysCount: 20,
    absentDaysCount: 1,
    leaveDaysCount: 2,
    lateArrivalsCount: 2,
    attendanceRate: 91.0,
    unitsProducedToday: 14200,
    qualityPassRate: 96.4,
    overtimeHoursMonth: 12.0,
  },
  {
    id: "emp_105",
    employeeId: "EMP-105",
    name: "Ananya Mishra",
    department: "Inventory",
    designation: "Warehouse Executive",
    shift: "General Shift",
    phone: "+91 99370 12840",
    email: "ananya.mishra@factory.com",
    joiningDate: "2022-11-04",
    status: "Active",
    todayAttendance: "Present",
    checkInTime: "08:50 AM",
    productivityScore: 91.0,
    presentDaysCount: 22,
    absentDaysCount: 0,
    leaveDaysCount: 1,
    lateArrivalsCount: 0,
    attendanceRate: 98.0,
    unitsProducedToday: 0,
    qualityPassRate: 97.5,
    overtimeHoursMonth: 6.5,
  },
  {
    id: "emp_106",
    employeeId: "EMP-106",
    name: "Rajesh Sharma",
    department: "Procurement",
    designation: "Procurement Executive",
    shift: "General Shift",
    phone: "+91 98450 77120",
    email: "rajesh.sharma@factory.com",
    joiningDate: "2021-02-18",
    status: "Active",
    todayAttendance: "Present",
    checkInTime: "08:55 AM",
    productivityScore: 93.4,
    presentDaysCount: 23,
    absentDaysCount: 0,
    leaveDaysCount: 0,
    lateArrivalsCount: 0,
    attendanceRate: 100.0,
    unitsProducedToday: 0,
    qualityPassRate: 98.0,
    overtimeHoursMonth: 9.0,
  },
  {
    id: "emp_107",
    employeeId: "EMP-107",
    name: "Marcus Brody",
    department: "Quality",
    designation: "Quality Inspector",
    shift: "Evening Shift",
    phone: "+91 94370 66140",
    email: "marcus.brody@factory.com",
    joiningDate: "2023-07-12",
    status: "Active",
    todayAttendance: "Present",
    checkInTime: "01:50 PM",
    productivityScore: 91.2,
    presentDaysCount: 21,
    absentDaysCount: 1,
    leaveDaysCount: 1,
    lateArrivalsCount: 1,
    attendanceRate: 94.8,
    unitsProducedToday: 9800,
    qualityPassRate: 97.8,
    overtimeHoursMonth: 10.5,
  },
  {
    id: "emp_108",
    employeeId: "EMP-108",
    name: "Ramesh Jena",
    department: "Production",
    designation: "Machine Operator",
    shift: "Morning Shift",
    phone: "+91 99380 44210",
    email: "ramesh.jena@factory.com",
    joiningDate: "2024-02-01",
    status: "On Leave",
    todayAttendance: "Leave",
    productivityScore: 86.0,
    presentDaysCount: 18,
    absentDaysCount: 2,
    leaveDaysCount: 3,
    lateArrivalsCount: 3,
    attendanceRate: 85.7,
    unitsProducedToday: 0,
    qualityPassRate: 94.2,
    overtimeHoursMonth: 4.0,
  },
  {
    id: "emp_109",
    employeeId: "EMP-109",
    name: "Debashis Rout",
    department: "Maintenance",
    designation: "Maintenance Technician",
    shift: "Evening Shift",
    phone: "+91 97760 33810",
    email: "debashis.rout@factory.com",
    joiningDate: "2023-09-15",
    status: "Active",
    todayAttendance: "Present",
    checkInTime: "02:15 PM",
    productivityScore: 88.0,
    presentDaysCount: 20,
    absentDaysCount: 1,
    leaveDaysCount: 2,
    lateArrivalsCount: 4,
    attendanceRate: 89.2,
    unitsProducedToday: 0,
    qualityPassRate: 95.0,
    overtimeHoursMonth: 16.0,
  },
  {
    id: "emp_110",
    employeeId: "EMP-110",
    name: "Kavita Sahoo",
    department: "Packaging",
    designation: "Production Operator",
    shift: "Night Shift",
    phone: "+91 98610 88720",
    email: "kavita.sahoo@factory.com",
    joiningDate: "2024-04-10",
    status: "Active",
    todayAttendance: "Present",
    checkInTime: "09:50 PM",
    productivityScore: 87.5,
    presentDaysCount: 19,
    absentDaysCount: 2,
    leaveDaysCount: 2,
    lateArrivalsCount: 1,
    attendanceRate: 88.4,
    unitsProducedToday: 11200,
    qualityPassRate: 95.8,
    overtimeHoursMonth: 11.0,
  },
  {
    id: "emp_111",
    employeeId: "EMP-111",
    name: "Subrat Mohapatra",
    department: "Production",
    designation: "Production Operator",
    shift: "Night Shift",
    phone: "+91 94370 22910",
    email: "subrat.m@factory.com",
    joiningDate: "2023-11-01",
    status: "Active",
    todayAttendance: "Absent",
    productivityScore: 82.0,
    presentDaysCount: 17,
    absentDaysCount: 4,
    leaveDaysCount: 2,
    lateArrivalsCount: 3,
    attendanceRate: 81.0,
    unitsProducedToday: 0,
    qualityPassRate: 93.5,
    overtimeHoursMonth: 8.0,
  },
  {
    id: "emp_112",
    employeeId: "EMP-112",
    name: "Smita Panigrahi",
    department: "HR",
    designation: "HR Executive",
    shift: "General Shift",
    phone: "+91 98200 11950",
    email: "smita.p@factory.com",
    joiningDate: "2022-06-20",
    status: "Active",
    todayAttendance: "Present",
    checkInTime: "08:58 AM",
    productivityScore: 94.0,
    presentDaysCount: 23,
    absentDaysCount: 0,
    leaveDaysCount: 0,
    lateArrivalsCount: 0,
    attendanceRate: 100.0,
    unitsProducedToday: 0,
    qualityPassRate: 99.0,
    overtimeHoursMonth: 4.0,
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "att_001",
    employeeId: "EMP-101",
    employeeName: "Tapan Nayak",
    department: "Production",
    shift: "Morning Shift",
    date: "2026-10-01",
    checkIn: "05:52 AM",
    checkOut: "02:15 PM",
    workingHours: 8.2,
    overtimeHours: 0.5,
    status: "Present",
  },
  {
    id: "att_002",
    employeeId: "EMP-102",
    employeeName: "Viktor Vance",
    department: "Maintenance",
    shift: "General Shift",
    date: "2026-10-01",
    checkIn: "08:45 AM",
    checkOut: "06:30 PM",
    workingHours: 9.5,
    overtimeHours: 1.5,
    status: "Present",
  },
  {
    id: "att_003",
    employeeId: "EMP-103",
    employeeName: "Elena Rostova",
    department: "Quality",
    shift: "Morning Shift",
    date: "2026-10-01",
    checkIn: "05:58 AM",
    checkOut: "02:00 PM",
    workingHours: 8.0,
    overtimeHours: 0.0,
    status: "Present",
  },
  {
    id: "att_004",
    employeeId: "EMP-104",
    employeeName: "Priya Sundaram",
    department: "Packaging",
    shift: "Morning Shift",
    date: "2026-10-01",
    checkIn: "06:22 AM",
    checkOut: "02:30 PM",
    workingHours: 8.0,
    overtimeHours: 0.5,
    status: "Late",
  },
  {
    id: "att_005",
    employeeId: "EMP-105",
    employeeName: "Ananya Mishra",
    department: "Inventory",
    shift: "General Shift",
    date: "2026-10-01",
    checkIn: "08:50 AM",
    checkOut: "05:10 PM",
    workingHours: 8.0,
    overtimeHours: 0.0,
    status: "Present",
  },
  {
    id: "att_006",
    employeeId: "EMP-107",
    employeeName: "Marcus Brody",
    department: "Quality",
    shift: "Evening Shift",
    date: "2026-10-01",
    checkIn: "01:50 PM",
    checkOut: "10:10 PM",
    workingHours: 8.2,
    overtimeHours: 0.5,
    status: "Present",
  },
  {
    id: "att_007",
    employeeId: "EMP-108",
    employeeName: "Ramesh Jena",
    department: "Production",
    shift: "Morning Shift",
    date: "2026-10-01",
    checkIn: "--",
    checkOut: "--",
    workingHours: 0,
    overtimeHours: 0,
    status: "Leave",
  },
  {
    id: "att_008",
    employeeId: "EMP-109",
    employeeName: "Debashis Rout",
    department: "Maintenance",
    shift: "Evening Shift",
    date: "2026-10-01",
    checkIn: "02:18 PM",
    checkOut: "11:00 PM",
    workingHours: 8.7,
    overtimeHours: 1.0,
    status: "Late",
  },
  {
    id: "att_009",
    employeeId: "EMP-111",
    employeeName: "Subrat Mohapatra",
    department: "Production",
    shift: "Night Shift",
    date: "2026-10-01",
    checkIn: "--",
    checkOut: "--",
    workingHours: 0,
    overtimeHours: 0,
    status: "Absent",
  },
];

export const INITIAL_SHIFTS: ShiftItem[] = [
  {
    id: "shift_001",
    shiftName: "Morning Shift",
    startTime: "06:00",
    endTime: "14:00",
    totalAssigned: 32,
    presentCount: 29,
    absentCount: 3,
    utilizationRate: 90.6,
    leadSupervisor: "Tapan Nayak",
  },
  {
    id: "shift_002",
    shiftName: "General Shift",
    startTime: "09:00",
    endTime: "17:00",
    totalAssigned: 18,
    presentCount: 18,
    absentCount: 0,
    utilizationRate: 100.0,
    leadSupervisor: "Viktor Vance",
  },
  {
    id: "shift_003",
    shiftName: "Evening Shift",
    startTime: "14:00",
    endTime: "22:00",
    totalAssigned: 22,
    presentCount: 19,
    absentCount: 3,
    utilizationRate: 86.4,
    leadSupervisor: "Marcus Brody",
  },
  {
    id: "shift_004",
    shiftName: "Night Shift",
    startTime: "22:00",
    endTime: "06:00",
    totalAssigned: 14,
    presentCount: 11,
    absentCount: 3,
    utilizationRate: 78.5,
    leadSupervisor: "Subrat Mohapatra",
  },
];

export const INITIAL_ALLOCATIONS: WorkforceAllocationItem[] = [
  {
    id: "alloc_001",
    category: "Biscuit Baking & Dough Mixing",
    department: "Production",
    requiredEmployees: 30,
    assignedEmployees: 27,
    availableEmployees: 25,
    utilizationRate: 92.5,
    hasShortage: true,
  },
  {
    id: "alloc_002",
    category: "Flow Wrapping & Carton Packing",
    department: "Packaging",
    requiredEmployees: 20,
    assignedEmployees: 18,
    availableEmployees: 16,
    utilizationRate: 88.0,
    hasShortage: true,
  },
  {
    id: "alloc_003",
    category: "In-line AQL & Sensory Lab",
    department: "Quality",
    requiredEmployees: 10,
    assignedEmployees: 10,
    availableEmployees: 10,
    utilizationRate: 100.0,
    hasShortage: false,
  },
  {
    id: "alloc_004",
    category: "Preventive Servicing & Bay Repair",
    department: "Maintenance",
    requiredEmployees: 8,
    assignedEmployees: 8,
    availableEmployees: 8,
    utilizationRate: 100.0,
    hasShortage: false,
  },
  {
    id: "alloc_005",
    category: "Dock Inflow & Finished Goods Storage",
    department: "Inventory",
    requiredEmployees: 8,
    assignedEmployees: 8,
    availableEmployees: 7,
    utilizationRate: 87.5,
    hasShortage: false,
  },
  {
    id: "alloc_006",
    category: "Vendor Purchase & Sourcing",
    department: "Procurement",
    requiredEmployees: 4,
    assignedEmployees: 4,
    availableEmployees: 4,
    utilizationRate: 100.0,
    hasShortage: false,
  },
  {
    id: "alloc_007",
    category: "Plant HR & Operations Admin",
    department: "HR",
    requiredEmployees: 6,
    assignedEmployees: 6,
    availableEmployees: 6,
    utilizationRate: 100.0,
    hasShortage: false,
  },
];

export const INITIAL_PRODUCTION_WORKFORCE: ProductionLineWorkforce[] = [
  {
    id: "pw_001",
    lineId: "Line-01",
    lineName: "Biscuit Line 1 (Continuous Tunnel)",
    assignedEmployees: 14,
    operatorsCount: 12,
    supervisorsCount: 2,
    currentShift: "Morning Shift",
    workforceUtilization: 100.0,
    status: "Fully Staffed",
    leadSupervisor: "Tapan Nayak",
  },
  {
    id: "pw_002",
    lineId: "Line-02",
    lineName: "Biscuit Line 2 (Rotary Deck)",
    assignedEmployees: 11,
    operatorsCount: 10,
    supervisorsCount: 1,
    currentShift: "Morning Shift",
    workforceUtilization: 84.6,
    status: "Understaffed",
    leadSupervisor: "Ramesh Jena",
  },
  {
    id: "pw_003",
    lineId: "Packaging-01",
    lineName: "High-Speed Flow Wrapper 1",
    assignedEmployees: 9,
    operatorsCount: 8,
    supervisorsCount: 1,
    currentShift: "Morning Shift",
    workforceUtilization: 100.0,
    status: "Fully Staffed",
    leadSupervisor: "Priya Sundaram",
  },
  {
    id: "pw_004",
    lineId: "Packaging-02",
    lineName: "Secondary Master Cartoner 2",
    assignedEmployees: 7,
    operatorsCount: 6,
    supervisorsCount: 1,
    currentShift: "Morning Shift",
    workforceUtilization: 77.8,
    status: "Understaffed",
    leadSupervisor: "Kavita Sahoo",
  },
];

export const INITIAL_OVERTIME_RECORDS: OvertimeRecord[] = [
  {
    id: "ot_001",
    employeeId: "EMP-102",
    employeeName: "Viktor Vance",
    department: "Maintenance",
    date: "2026-10-01",
    regularHours: 8.0,
    overtimeHours: 4.5,
    totalHours: 12.5,
    reason: "Emergency belt alignment & suctions overhaul on Packaging Machine 2.",
    approvalStatus: "Approved",
    isHighOvertime: true,
  },
  {
    id: "ot_002",
    employeeId: "EMP-109",
    employeeName: "Debashis Rout",
    department: "Maintenance",
    date: "2026-10-01",
    regularHours: 8.0,
    overtimeHours: 5.0,
    totalHours: 13.0,
    reason: "Radiant heater thermocouple replacement during oven cool-down window.",
    approvalStatus: "Approved",
    isHighOvertime: true,
  },
  {
    id: "ot_003",
    employeeId: "EMP-104",
    employeeName: "Priya Sundaram",
    department: "Packaging",
    date: "2026-09-30",
    regularHours: 8.0,
    overtimeHours: 2.5,
    totalHours: 10.5,
    reason: "Completed high-volume Cream Biscuit rush packing run for Dispatch 042.",
    approvalStatus: "Approved",
    isHighOvertime: false,
  },
  {
    id: "ot_004",
    employeeId: "EMP-101",
    employeeName: "Tapan Nayak",
    department: "Production",
    date: "2026-09-30",
    regularHours: 8.0,
    overtimeHours: 3.0,
    totalHours: 11.0,
    reason: "Supervised extended shift changeover for Classic Butter batch change.",
    approvalStatus: "Pending",
    isHighOvertime: false,
  },
  {
    id: "ot_005",
    employeeId: "EMP-110",
    employeeName: "Kavita Sahoo",
    department: "Packaging",
    date: "2026-09-29",
    regularHours: 8.0,
    overtimeHours: 4.5,
    totalHours: 12.5,
    reason: "Late freight dock loading support and carton sealing verification.",
    approvalStatus: "Pending",
    isHighOvertime: true,
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequestRecord[] = [
  {
    id: "lr_001",
    requestId: "LR-2026-081",
    employeeId: "EMP-108",
    employeeName: "Ramesh Jena",
    department: "Production",
    leaveType: "Sick",
    startDate: "2026-10-01",
    endDate: "2026-10-03",
    daysCount: 3,
    reason: "Viral fever and acute throat infection. Doctor prescription submitted.",
    status: "Approved",
    appliedDate: "2026-09-30",
  },
  {
    id: "lr_002",
    requestId: "LR-2026-082",
    employeeId: "EMP-111",
    employeeName: "Subrat Mohapatra",
    department: "Production",
    leaveType: "Casual",
    startDate: "2026-10-05",
    endDate: "2026-10-07",
    daysCount: 3,
    reason: "Family function in home village.",
    status: "Pending",
    appliedDate: "2026-10-01",
  },
  {
    id: "lr_003",
    requestId: "LR-2026-083",
    employeeId: "EMP-107",
    employeeName: "Marcus Brody",
    department: "Quality",
    leaveType: "Earned",
    startDate: "2026-10-12",
    endDate: "2026-10-16",
    daysCount: 5,
    reason: "Annual planned vacation.",
    status: "Pending",
    appliedDate: "2026-09-28",
  },
  {
    id: "lr_004",
    requestId: "LR-2026-084",
    employeeId: "EMP-104",
    employeeName: "Priya Sundaram",
    department: "Packaging",
    leaveType: "Emergency",
    startDate: "2026-09-26",
    endDate: "2026-09-27",
    daysCount: 2,
    reason: "Personal family medical urgency.",
    status: "Approved",
    appliedDate: "2026-09-25",
  },
  {
    id: "lr_005",
    requestId: "LR-2026-085",
    employeeId: "EMP-109",
    employeeName: "Debashis Rout",
    department: "Maintenance",
    leaveType: "Casual",
    startDate: "2026-09-20",
    endDate: "2026-09-22",
    daysCount: 3,
    reason: "Personal travel.",
    status: "Rejected",
    rejectionReason: "Critical maintenance overhaul scheduled on Baking Oven 2 during this period.",
    appliedDate: "2026-09-18",
  },
];

export const INITIAL_WORKFORCE_ALERTS: WorkforceAlert[] = [
  {
    id: "wf_alt_001",
    severity: "High",
    targetEntity: "Production Line 2",
    category: "Staffing",
    reason: "⚠ Production Line 2 is understaffed for Morning Shift (11 assigned vs 13 required).",
    recommendedAction: "Cross-deploy 2 auxiliary operators from Warehouse/Packaging reserve pool.",
    timestamp: "25 mins ago",
  },
  {
    id: "wf_alt_002",
    severity: "Medium",
    targetEntity: "Maintenance Dept",
    category: "Overtime",
    reason: "⚠ 3 Maintenance technicians have exceeded 15 hours of cumulative overtime this week.",
    recommendedAction: "Rotate next preventive maintenance roster with General Shift technician pool.",
    timestamp: "1 hour ago",
  },
  {
    id: "wf_alt_003",
    severity: "Medium",
    targetEntity: "Packaging-02",
    category: "Staffing",
    reason: "⚠ Packaging-02 requires additional operators to maintain high-speed cartoning target.",
    recommendedAction: "Assign 1 floating operator from Secondary Packaging bay.",
    timestamp: "3 hours ago",
  },
  {
    id: "wf_alt_004",
    severity: "Low",
    targetEntity: "HR Dept",
    category: "Leave",
    reason: "⚠ 2 pending leave requests require supervisor sign-off before shift schedule lock.",
    recommendedAction: "Review leave calendar and confirm replacement coverage.",
    timestamp: "4 hours ago",
  },
];

export const ATTENDANCE_TREND_30_DAYS: AttendanceTrendPoint[] = [
  { date: "Sep 02", present: 76, absent: 5, leave: 5, late: 2, attendanceRate: 88.4 },
  { date: "Sep 04", present: 78, absent: 4, leave: 4, late: 3, attendanceRate: 90.7 },
  { date: "Sep 06", present: 74, absent: 6, leave: 6, late: 4, attendanceRate: 86.0 },
  { date: "Sep 08", present: 80, absent: 2, leave: 4, late: 1, attendanceRate: 93.0 },
  { date: "Sep 10", present: 79, absent: 3, leave: 4, late: 2, attendanceRate: 91.8 },
  { date: "Sep 12", present: 77, absent: 4, leave: 5, late: 3, attendanceRate: 89.5 },
  { date: "Sep 14", present: 75, absent: 5, leave: 6, late: 5, attendanceRate: 87.2 },
  { date: "Sep 16", present: 81, absent: 2, leave: 3, late: 1, attendanceRate: 94.1 },
  { date: "Sep 18", present: 78, absent: 4, leave: 4, late: 2, attendanceRate: 90.7 },
  { date: "Sep 20", present: 80, absent: 3, leave: 3, late: 2, attendanceRate: 93.0 },
  { date: "Sep 22", present: 76, absent: 5, leave: 5, late: 4, attendanceRate: 88.4 },
  { date: "Sep 24", present: 82, absent: 1, leave: 3, late: 1, attendanceRate: 95.3 },
  { date: "Sep 26", present: 79, absent: 3, leave: 4, late: 2, attendanceRate: 91.8 },
  { date: "Sep 28", present: 77, absent: 4, leave: 5, late: 3, attendanceRate: 89.5 },
  { date: "Sep 30", present: 75, absent: 5, leave: 6, late: 4, attendanceRate: 87.2 },
  { date: "Oct 01", present: 74, absent: 5, leave: 7, late: 3, attendanceRate: 86.0 },
];

export const DEPARTMENT_PRODUCTIVITY_BENCHMARKS: DepartmentProductivityItem[] = [
  { department: "Production", productivity: 91.4, unitsPerWorker: 1250, avgHours: 8.2, overtimeHours: 42, color: "#10b981" },
  { department: "Quality", productivity: 95.8, unitsPerWorker: 980, avgHours: 8.0, overtimeHours: 18, color: "#06b6d4" },
  { department: "Maintenance", productivity: 94.0, unitsPerWorker: 0, avgHours: 8.8, overtimeHours: 38, color: "#f59e0b" },
  { department: "Packaging", productivity: 88.6, unitsPerWorker: 1100, avgHours: 8.3, overtimeHours: 24, color: "#a855f7" },
  { department: "Warehouse", productivity: 91.0, unitsPerWorker: 850, avgHours: 8.1, overtimeHours: 12, color: "#3b82f6" },
];
